type Category {
    features: [Feature!] @hasMany
    id: ID!
    parent_id: Int!
    is_active: Boolean!
    is_parent: Boolean!
    title: String
    title_short: String
    slug: String
    seo_title: String
    seo_description: String
    seo_keywords: String
    description: String

    images: String @rename(attribute: "rawImages")
    settings: String @rename(attribute: "rawSettings")
}

input CategoryInput {
    parent_id: Int!
    is_active: Boolean
    is_parent: Boolean
}

extend type Query {
    category(id: ID! @eq): Category @find
    categories: [Category!]! @all
}

extend type Mutation {
    createCategory(input: ProductInput @spread): Product @create
}
