type Feature {
    children: [Feature!] @hasMany
    id: ID!
    key: String!
    parent_id: Int!
    category_id: Int!
    is_parent: Boolean!
    is_required: Boolean!
    is_filter: Boolean!
    ord: Int
    title: String
    slug: String
    type: String
    hint: String
    units: String
    values: String @rename(attribute: "rawValues")
}
