type Setting {
    id: ID!
    title: String
    key: String
    value: String
    comment: String
    value: String! @rename(attribute: "rawValue")
}

input SettingInput {
    id: ID!
}

extend type Query {
    setting(id: ID! @eq): Setting @find
    settings: [Setting!]! @all
}


