type Variant {
    id: ID
    product_id: Int
    category_id: Int
    is_active: Boolean
    is_stock: Boolean
    is_sale: Boolean
    price: Float
    surcharge: Float
    weight: Float
    code: String
    barcode: String

    images: String
    parameters: String
    stocks: String
}

extend type Query {
    Variant(id: ID! @eq): Variant @find
    Variants: [Variant!]! @all
}
